Repository Progmong/Progmong-BE, pull requests merged in 2025-06, with the labels that each got.

#7 Feat/#5
  src/main/java/com/progmong/ProgmongApplication.java
  src/main/java/com/progmong/api/pet/controller/UserPetController.java
  src/main/java/com/progmong/api/pet/dto/PetRegisterRequestDto.java
  src/main/java/com/progmong/api/pet/repository/PetRepository.java
  src/main/java/com/progmong/api/pet/service/UserPetService.java
  src/main/java/com/progmong/common/response/ErrorStatus.java
  src/main/java/com/progmong/common/response/SuccessStatus.java
Labels: feat

#15 Feat/#12
  src/main/java/com/progmong/api/pet/service/UserPetService.java
  src/main/java/com/progmong/api/tag/controller/InterestTagController.java
  src/main/java/com/progmong/api/tag/dto/InterestTagResponseDto.java
  src/main/java/com/progmong/api/tag/dto/InterestTagUpdateRequestDto.java
  src/main/java/com/progmong/api/tag/repository/InterestTagRepository.java
  src/main/java/com/progmong/api/tag/repository/TagRepository.java
  src/main/java/com/progmong/api/tag/service/InterestTagService.java
  src/main/java/com/progmong/common/response/SuccessStatus.java
Labels: feat

#14 Feat/#8
  build.gradle
  src/main/java/com/progmong/ProgmongApplication.java
  src/main/java/com/progmong/api/user/Controller/UserController.java
  src/main/java/com/progmong/api/user/dto/EmailVerificationCodeRequestDto.java
  src/main/java/com/progmong/api/user/dto/EmailVerificationRequestDto.java
  src/main/java/com/progmong/api/user/dto/PasswordResetConfirmDto.java
  src/main/java/com/progmong/api/user/dto/PasswordResetRequestDto.java
  src/main/java/com/progmong/api/user/dto/UserInfoResponseDto.java
  src/main/java/com/progmong/api/user/dto/UserLoginRequestDto.java
  src/main/java/com/progmong/api/user/dto/UserLoginResponseDto.java
  src/main/java/com/progmong/api/user/dto/UserRegisterRequestDto.java
  src/main/java/com/progmong/api/user/entity/EmailVerification.java
  src/main/java/com/progmong/api/user/entity/PasswordReset.java
  src/main/java/com/progmong/api/user/entity/User.java
  src/main/java/com/progmong/api/user/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/progmong/api/user/jwt/service/JwtService.java
  src/main/java/com/progmong/api/user/repository/EmailVerificationRepository.java
  src/main/java/com/progmong/api/user/repository/PasswordResetRepository.java
  src/main/java/com/progmong/api/user/repository/UserRepository.java
  src/main/java/com/progmong/api/user/service/EmailService.java
  src/main/java/com/progmong/api/user/service/UserService.java
  src/main/java/com/progmong/common/config/jwt/JwtConfig.java
  src/main/java/com/progmong/common/config/mail/MailConfig.java
  src/main/java/com/progmong/common/config/security/SecurityConfig.java
  src/main/java/com/progmong/common/config/security/SecurityUser.java
  src/main/java/com/progmong/common/config/swagger/SwaggerConfig.java
  src/main/java/com/progmong/common/response/ErrorStatus.java
  src/main/java/com/progmong/common/response/SuccessStatus.java
Labels: feat

#22 Feat/#21 Solved.ac 인증 API 추가
  src/main/java/com/progmong/api/user/Controller/SolvedacController.java
  src/main/java/com/progmong/api/user/dto/UserInfoResponseDto.java
  src/main/java/com/progmong/api/user/dto/UserRegisterRequestDto.java
  src/main/java/com/progmong/api/user/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/progmong/api/user/repository/UserRepository.java
  src/main/java/com/progmong/api/user/service/SolvedacService.java
  src/main/java/com/progmong/api/user/service/UserService.java
  src/main/java/com/progmong/common/config/RestTemplateConfig.java
  src/main/java/com/progmong/common/config/security/SecurityConfig.java
  src/main/java/com/progmong/common/config/security/SecurityUser.java
Labels: feat

#23 [REFAC] JWT 기반 사용자 인증으로 관심 태그/펫 등록 기능 수정
  src/main/java/com/progmong/api/pet/controller/UserPetController.java
  src/main/java/com/progmong/api/pet/dto/PetRegisterRequestDto.java
  src/main/java/com/progmong/api/pet/service/UserPetService.java
  src/main/java/com/progmong/api/tag/controller/InterestTagController.java
  src/main/java/com/progmong/api/tag/dto/InterestTagResponseDto.java
  src/main/java/com/progmong/api/tag/dto/InterestTagUpdateRequestDto.java
Labels: refactor

#28 refactor(user): 닉네임 중복 에러 메세지 추가
  src/main/java/com/progmong/api/user/service/UserService.java
  src/main/java/com/progmong/common/response/ErrorStatus.java
Labels: refactor

#29 refactor(explore): Explore 로직에 JWT 기반 사용자 인증 적용
  src/main/java/com/progmong/api/explore/controller/ExploreController.java
  src/main/java/com/progmong/api/user/service/UserService.java
  src/main/java/com/progmong/common/response/SuccessStatus.java
Labels: feat, refactor

#30 Feat/#26 사용자 펫 정보 불러오기
  src/main/java/com/progmong/api/pet/controller/UserPetController.java
  src/main/java/com/progmong/api/pet/dto/UserPetFullDto.java
  src/main/java/com/progmong/api/pet/service/UserPetService.java
  src/main/java/com/progmong/common/response/SuccessStatus.java
Labels: feat
